### ISSUE TITLE
Move KFENCE internals info to kernel docs

### ISSUE THREAD

**Issue by xairy** [google/kernel-sanitizers#216]
Currently, KFENCE.md contains information that possibly extends/duplicates kernel's documentation about KFENCE. It makes sense to move/drop this duplicate information from KFENCE.md.

**Comment by melver** [comment]
It duplicates the kernel's documentation. It was intended as a super high-level overview for those who don't want to read the kernel's doc.

Something like a "1-pager" when communicating what KFENCE is. I think there's nothing wrong with duplicating some info here, but perhaps we can delete some more info (such as the code snippet) to make it even more crisp.

**Comment by xairy** [comment]
Ah, I see. Makes sense. Maybe we need a 1-pager like this for other tools as well.
