### ISSUE TITLE
Does kernel hwasan support short granules？

### ISSUE THREAD

**Issue by zizhiyoumu-fuzz** [google/kernel-sanitizers#218]
While I used hwasan to test kernel, I open the CONFIG_KASAN_MODULE_TEST to test.
I found that short granules doesn't work well for linux kernel.
I also open the hwasan-use-short-granules=1, it doesn't work.
Does kernel hwasan support short granules？
If I want open the feature, how to deal with it?
Thank you.

**Comment by xairy** [comment]
Hi,

No, SW_TAGS KASAN does not support short granules. There's [a bug] filed for this.

If you want to implement support for this, you'll need to look into the [userspace implementation](https://clang.llvm.org/docs/HardwareAssistedAddressSanitizerDesign.html#short-granules) and replicate it for the kernel.

Thanks!
