### ISSUE TITLE
does hwasan need to enable ksan for x86_64 linux gnu? 

### ISSUE THREAD

**Issue by trcrsired** [google/kernel-sanitizers#221]
I want to try hwasan on x86, is that possible?

**Comment by xairy** [comment]
I assume you're talking about HWASan for the Linux kernel, aka SW_TAGS KASAN. No, it's not supported on x86. It's possible to add support for it based on Intel LAM, but this was never done. Thanks!

**Comment by trcrsired** [comment]
> I assume you're talking about HWASan for the Linux kernel, aka SW_TAGS KASAN. No, it's not supported on x86. It's possible to add support for it based on Intel LAM, but this was never done. Thanks!

not kernel itself. i mean the user space hwasan

**Comment by trcrsired** [comment]
hello?

**Comment by trcrsired** [comment]
@xairy

**Comment by xairy** [comment]
No idea about userspace, but the page you linked also mentions needing Intel LAM. So would assume you can just enable it via `-fsanitize=hwaddress` on systems that support LAM. I see you already the same question [here](https://github.com/google/sanitizers/issues/1789), hopefully, someone will respond there.
